// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "./Verifier.sol"; // Generated by SnarkJS

contract AgeRestricted {
    Groth16Verifier verifier;

    constructor() {
        verifier = new Groth16Verifier();
    }

    function verifyAge(uint[2] calldata proofA, uint[2][2] calldata proofB, uint[2] calldata proofC, uint[3] calldata publicSignals) public view returns (bool) {
        
        
        return verifier.verifyProof(proofA, proofB, proofC, publicSignals);
    }
}